ERP_System-main/ERP-Project-main/University_Registration/University_Registration/Controllers/SubjectsAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using University_Registration.Models;

namespace University_Registration.Controllers
{
    public class SubjectsAdminController : Controller
    {
        private ERP_SystemEntities1 db = new ERP_SystemEntities1();
        [Authorize(Roles = "Admin")]

        // GET: SubjectsAdmin
        public ActionResult Index()
        {
            var subjects = db.Subjects.Include(s => s.Major);
            return View(subjects.ToList());
        }

        [ActionName("Index")]
        [HttpPost]
        public ActionResult Index2(string search)
        {
            var subjects = db.Subjects.Where(n=>n.Name.Contains(search)).Include(s => s.Major);
            return View(subjects.ToList());
        }

        // GET: SubjectsAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // GET: SubjectsAdmin/Create
        public ActionResult Create()
        {
            ViewBag.Major_ID = new SelectList(db.Majors, "Major_ID", "Name");
            return View();
        }

        // POST: SubjectsAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Subject_ID,Name,Description,Major_ID,NumHour,SubjectView")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                subject.Subject_ID = Convert.ToInt32(Session["id"]);
                db.Subjects.Add(subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Major_ID = new SelectList(db.Majors, "Major_ID", "Name", subject.Major_ID);
            return View(subject);
        }

        // GET: SubjectsAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            ViewBag.Major_ID = new SelectList(db.Majors, "Major_ID", "Name", subject.Major_ID);
            return View(subject);
        }

        // POST: SubjectsAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Subject_ID,Name,Description,Major_ID,NumHour,SubjectView")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Major_ID = new SelectList(db.Majors, "Major_ID", "Name", subject.Major_ID);
            return View(subject);
        }

        // GET: SubjectsAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // POST: SubjectsAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {

                Subject subject = db.Subjects.Find(id);
                db.Subjects.Remove(subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("ErrorAdmin");
            }
        
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ERP_System-main/ERP-Project-main/University_Registration/University_Registration/Views/SubjectsAdmin/Create.cshtml
@model University_Registration.Models.Subject

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Adminlayout2.cshtml";
}

@section header{

    <a href="#" class="nav-link">Courses</a>

}
@section active{


    <ul class="side-menu top">
        <li>
            <a href="/FacilitiesAdmin/Index">
                <i class="fa-solid fa-building-columns"></i>
                <span class="text">Facilities</span>
            </a>
        </li>
        <li>
            <a href="/MajorsAdmin/Index">
                <i class="fa-solid fa-graduation-cap"></i>
                <span class="text">Majors</span>
            </a>
        </li>

        <li class="active">
            <a href="/SubjectsAdmin/Index">
                <i class="fa-solid fa-book"></i>
                <span class="text">Courses</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Index">
                <i class="fa-sharp fa-solid fa-users"></i>
                <span class="text">Students</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Acceptt">
                <i class="fa fa-check" aria-hidden="true"></i>
                <span class="text">Accept Student</span>
            </a>
        </li>
        <li>
            <a href="/StudentsAdmin/Rejectt">
                <i class="fa fa-ban" aria-hidden="true"></i>
                <span class="text">Reject Student</span>
            </a>
        </li>

        <li>
            <a href="/SubjectRegistrationsAdmin/Index">
                <i class="fa-solid fa-money-bill"></i>
                <span class="text">Payment</span>
            </a>
        </li>
        <li>
            <a href="/SubjectRegistrationsAdmin/Index2">
                <i class="fa-solid fa-dollar-sign"></i>
                <span class="text">Progress Payment</span>
            </a>
        </li>
        <li>
            <a href="/staticAdmin/Index">
                <i class="fas fa-chart-bar"></i>
                <span class="text">statistics </span>
            </a>
        </li>
    </ul>


}
<style>
    tr td:first-child {
        padding: 1rem;
    }
</style>

@using (Html.BeginForm("Create", "SubjectsAdmin"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })

            </td>
            <td>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })

            </td>
            <td>
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Major_ID, "Major_ID", htmlAttributes: new { @class = "control-label col-md-2" })

            </td>
            <td>
                @Html.DropDownList("Major_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Major_ID, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.NumHour, htmlAttributes: new { @class = "control-label col-md-2" })

            </td>
            <td>
                @Html.EditorFor(model => model.NumHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumHour, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.SubjectView)

            </td>
            <td>
                @Html.EditorFor(model => model.SubjectView, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubjectView, "", new { @class = "text-danger" })
            </td>

        </tr>
    </table>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">

            <input type="submit" value="Create" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })

        </div>
    </div>

}

ERP_System-main/ERP-Project-main/University_Registration/University_Registration/Views/SubjectsAdmin/Delete.cshtml
@model University_Registration.Models.Subject

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Adminlayout2.cshtml";
}

@section header{

    <a href="#" class="nav-link">Courses</a>

}
@section active{


    <ul class="side-menu top">
        <li>
            <a href="/FacilitiesAdmin/Index">
                <i class="fa-solid fa-building-columns"></i>
                <span class="text">Facilities</span>
            </a>
        </li>
        <li>
            <a href="/MajorsAdmin/Index">
                <i class="fa-solid fa-graduation-cap"></i>
                <span class="text">Majors</span>
            </a>
        </li>

        <li class="active">
            <a href="/SubjectsAdmin/Index">
                <i class="fa-solid fa-book"></i>
                <span class="text">Courses</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Index">
                <i class="fa-sharp fa-solid fa-users"></i>
                <span class="text">Students</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Acceptt">
                <i class="fa fa-check" aria-hidden="true"></i>
                <span class="text">Accept Student</span>
            </a>
        </li>
        <li>
            <a href="/StudentsAdmin/Rejectt">
                <i class="fa fa-ban" aria-hidden="true"></i>
                <span class="text">Reject Student</span>
            </a>
        </li>

        <li>
            <a href="/SubjectRegistrationsAdmin/Index">
                <i class="fa-solid fa-money-bill"></i>
                <span class="text">Payment</span>
            </a>
        </li>
        <li>
            <a href="/SubjectRegistrationsAdmin/Index2">
                <i class="fa-solid fa-dollar-sign"></i>
                <span class="text">Progress Payment</span>
            </a>
        </li>
        <li>
            <a href="/staticAdmin/Index">
                <i class="fas fa-chart-bar"></i>
                <span class="text">statistics </span>
            </a>
        </li>
    </ul>


}
<style>
    tr td:first-child {
        padding: 1rem;
    }
</style>

<h3 style="margin-top:2%">Are you sure you want to delete this?</h3>

<table>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Name)
        </td>

        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
    </tr>
    <tr>

        <td>
            @Html.DisplayNameFor(model => model.Description)
        </td>

        <td>
            @Html.DisplayFor(model => model.Description)
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.NumHour)
        </td>

        <td>
            @Html.DisplayFor(model => model.NumHour)
        </td>
    </tr>

    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Major.Name)
        </td>

        <td>
            @Html.DisplayFor(model => model.Major.Name)
        </td>
    </tr>
</table>







@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" />
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
    </div>
}
</div>

ERP_System-main/ERP-Project-main/University_Registration/University_Registration/Views/SubjectsAdmin/Details.cshtml
@model University_Registration.Models.Subject

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Adminlayout2.cshtml";
}


@section header{

    <a href="#" class="nav-link">Courses</a>

}
@section active{


    <ul class="side-menu top">
        <li>
            <a href="/FacilitiesAdmin/Index">
                <i class="fa-solid fa-building-columns"></i>
                <span class="text">Facilities</span>
            </a>
        </li>
        <li>
            <a href="/MajorsAdmin/Index">
                <i class="fa-solid fa-graduation-cap"></i>
                <span class="text">Majors</span>
            </a>
        </li>

        <li class="active">
            <a href="/SubjectsAdmin/Index">
                <i class="fa-solid fa-book"></i>
                <span class="text">Courses</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Index">
                <i class="fa-sharp fa-solid fa-users"></i>
                <span class="text">Students</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Acceptt">
                <i class="fa fa-check" aria-hidden="true"></i>
                <span class="text">Accept Student</span>
            </a>
        </li>
        <li>
            <a href="/StudentsAdmin/Rejectt">
                <i class="fa fa-ban" aria-hidden="true"></i>
                <span class="text">Reject Student</span>
            </a>
        </li>

        <li>
            <a href="/SubjectRegistrationsAdmin/Index">
                <i class="fa-solid fa-money-bill"></i>
                <span class="text">Payment</span>
            </a>
        </li>
        <li>
            <a href="/SubjectRegistrationsAdmin/Index2">
                <i class="fa-solid fa-dollar-sign"></i>
                <span class="text">Progress Payment</span>
            </a>
        </li>
        <li>
            <a href="/staticAdmin/Index">
                <i class="fas fa-chart-bar"></i>
                <span class="text">statistics </span>
            </a>
        </li>
    </ul>


}
<style>
    tr td:first-child {
        padding: 1rem;
    }
</style>


<table>
    <tr>
        <td>

            @Html.DisplayNameFor(model => model.Name)




        </td>
        <td>
            @Html.DisplayFor(model => model.Name)

        </td>
    </tr>

    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Description)
        </td>

        <td>
            @Html.DisplayFor(model => model.Description)
        </td>
    </tr>
    <tr>
        <td>
            Number of Hour
        </td>

        <td>
            @Html.DisplayFor(model => model.NumHour)
        </td>
    </tr>




    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Major.Name)
        </td>

        <td>
            @Html.DisplayFor(model => model.Major.Name)
        </td>
    </tr>


</table>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Subject_ID }, new { @class = "btn btn-info" })
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</p>

ERP_System-main/ERP-Project-main/University_Registration/University_Registration/Views/SubjectsAdmin/Edit.cshtml
@model University_Registration.Models.Subject

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Adminlayout2.cshtml";
}

@section header{

    <a href="#" class="nav-link">Courses</a>

}
@section active{


    <ul class="side-menu top">
        <li>
            <a href="/FacilitiesAdmin/Index">
                <i class="fa-solid fa-building-columns"></i>
                <span class="text">Facilities</span>
            </a>
        </li>
        <li>
            <a href="/MajorsAdmin/Index">
                <i class="fa-solid fa-graduation-cap"></i>
                <span class="text">Majors</span>
            </a>
        </li>

        <li class="active">
            <a href="/SubjectsAdmin/Index">
                <i class="fa-solid fa-book"></i>
                <span class="text">Courses</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Index">
                <i class="fa-sharp fa-solid fa-users"></i>
                <span class="text">Students</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Acceptt">
                <i class="fa fa-check" aria-hidden="true"></i>
                <span class="text">Accept Student</span>
            </a>
        </li>
        <li>
            <a href="/StudentsAdmin/Rejectt">
                <i class="fa fa-ban" aria-hidden="true"></i>
                <span class="text">Reject Student</span>
            </a>
        </li>

        <li>
            <a href="/SubjectRegistrationsAdmin/Index">
                <i class="fa-solid fa-money-bill"></i>
                <span class="text">Payment</span>
            </a>
        </li>
        <li>
            <a href="/SubjectRegistrationsAdmin/Index2">
                <i class="fa-solid fa-dollar-sign"></i>
                <span class="text">Progress Payment</span>
            </a>
        </li>
        <li>
            <a href="/staticAdmin/Index">
                <i class="fas fa-chart-bar"></i>
                <span class="text">statistics </span>
            </a>
        </li>
    </ul>


}
<style>
    tr td:first-child {
        padding: 1rem;
    }
</style>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Subject_ID)
    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })

            </td>
            <td>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })

            </td>
            <td>

                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                Major Name

            </td>
            <td>
                @Html.DropDownList("Major_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Major_ID, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                Number of Hour

            </td>
            <td>
                @Html.EditorFor(model => model.NumHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumHour, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.SubjectView, htmlAttributes: new { @class = "control-label col-md-2" })

            </td>
            <td>
                @Html.EditorFor(model => model.SubjectView, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubjectView, "", new { @class = "text-danger" })
            </td>
        </tr>

    </table>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })

        </div>
    </div>

}

ERP_System-main/ERP-Project-main/University_Registration/University_Registration/Views/SubjectsAdmin/Index.cshtml
@model IEnumerable<University_Registration.Models.Subject>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Adminlayout2.cshtml";
}


@section header{

    <a href="#" class="nav-link">Courses</a>

}

@section active{


    <ul class="side-menu top">
        <li>
            <a href="/FacilitiesAdmin/Index">
                <i class="fa-solid fa-building-columns"></i>
                <span class="text">Facilities</span>
            </a>
        </li>
        <li>
            <a href="/MajorsAdmin/Index">
                <i class="fa-solid fa-graduation-cap"></i>
                <span class="text">Majors</span>
            </a>
        </li>

        <li class="active">
            <a href="/SubjectsAdmin/Index">
                <i class="fa-solid fa-book"></i>
                <span class="text">Courses</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Index">
                <i class="fa-sharp fa-solid fa-users"></i>
                <span class="text">Students</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Acceptt">
                <i class="fa fa-check" aria-hidden="true"></i>
                <span class="text">Accept Student</span>
            </a>
        </li>
        <li>
            <a href="/StudentsAdmin/Rejectt">
                <i class="fa fa-ban" aria-hidden="true"></i>
                <span class="text">Reject Student</span>
            </a>
        </li>

        <li>
            <a href="/SubjectRegistrationsAdmin/Index">
                <i class="fa-solid fa-money-bill"></i>
                <span class="text">Payment</span>
            </a>
        </li>
        <li>
            <a href="/SubjectRegistrationsAdmin/Index2">
                <i class="fa-solid fa-dollar-sign"></i>
                <span class="text">Progress Payment</span>
            </a>
        </li>
        <li>
            <a href="/staticAdmin/Index">
                <i class="fas fa-chart-bar"></i>
                <span class="text">statistics </span>
            </a>
        </li>
    </ul>


}

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-info" })
</p>

@using (Html.BeginForm("Index2"))
{
    <div class="input-group justify-center">
        <div class="form-outline">
            <input type="search" id="form1" name="search" class="form-control" placeholder="Seach by Course Name" />
        </div>
        <input type="Submit" value="Search" class="btn btn-secondary" style="margin-bottom:1%" />
    </div>
}

<table class="table table-responsive table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            Number of Hour
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubjectView)
        </th>
        <th>
            Major Name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumHour)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubjectView)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Major.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Subject_ID }, new { @class = "btn btn-success" })
                @Html.ActionLink("Details", "Details", new { id = item.Subject_ID }, new { @class = "btn btn-info" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Subject_ID }, new { @class = "btn btn-danger" })
                @Html.ActionLink("Sections", "Index", "SectionsAdmin", new { newid = item.Subject_ID }, new { @class = "btn btn-secondary" })

            </td>
        </tr>
    }

</table>